#!/usr/bin/env php
<?php

/**
 * This file is part of the Phalcon Developer Tools.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use Phalcon\DevTools\Commands\Builtin\AllModels;
use Phalcon\DevTools\Commands\Builtin\Console;
use Phalcon\DevTools\Commands\Builtin\Controller;
use Phalcon\DevTools\Commands\Builtin\Enumerate;
use Phalcon\DevTools\Commands\Builtin\Info;
use Phalcon\DevTools\Commands\Builtin\Migration;
use Phalcon\DevTools\Commands\Builtin\Model;
use Phalcon\DevTools\Commands\Builtin\Module;
use Phalcon\DevTools\Commands\Builtin\Project;
use Phalcon\DevTools\Commands\Builtin\Scaffold;
use Phalcon\DevTools\Commands\Builtin\Serve;
use Phalcon\DevTools\Commands\Builtin\Webtools;
use Phalcon\DevTools\Commands\CommandsListener;
use Phalcon\DevTools\Exception\PDODriverNotFoundException;
use Phalcon\DevTools\Commands\DotPhalconMissingException;
use Phalcon\DevTools\Script;
use Phalcon\DevTools\Script\Color;
use Phalcon\DevTools\Version;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Exception as PhalconException;

try {
    require dirname(__FILE__) . '/bootstrap/autoload.php';

    $vendor = sprintf('Phalcon DevTools (%s)', Version::get());
    print PHP_EOL . Color::colorize($vendor, Color::FG_GREEN, Color::AT_BOLD) . PHP_EOL . PHP_EOL;

    $eventsManager = new EventsManager();
    $eventsManager->attach('command', new CommandsListener());
    $script = new Script($eventsManager);

    $commandsToEnable = [
        Info::class,
        Enumerate::class,
        Controller::class,
        Module::class,
        Model::class,
        AllModels::class,
        Project::class,
        Scaffold::class,
        Migration::class,
        Webtools::class,
        Serve::class,
        Console::class,
    ];

    $script->loadUserScripts();

    foreach ($commandsToEnable as $command) {
        $script->attach(new $command($script, $eventsManager));
    }

    $script->run();
} catch (DotPhalconMissingException $e) {
    fwrite(STDERR, Color::info($e->getMessage() . " " . $e->scanPathMessage()));
    if ($e->promptResolution()) {
        $script->run();
    } else {
        exit(1);
    }
} catch (PhalconException $e) {
    fwrite(STDERR, Color::error($e->getMessage()) . PHP_EOL);
    exit(1);
} catch (PDODriverNotFoundException $e) {
    $e->writeNicelyFormattedErrorOutput();
    fwrite(STDERR, 'Backtrace:'. PHP_EOL);
    fwrite(STDERR, $e->getTraceAsString() . PHP_EOL);
    exit(1);
} catch (Exception $e) {
    fwrite(STDERR, 'ERROR: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
