#!/usr/bin/env php
<?php

/*
  +------------------------------------------------------------------------+
  | Phalcon Developer Tools                                                |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2016 Phalcon Team (https://www.phalconphp.com)      |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file LICENSE.txt.                             |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  |          Serghei Iakovlev <serghei@phalconphp.com>                     |
  +------------------------------------------------------------------------+
*/

use Phalcon\DevTools\Commands\Builtin\AllModels;
use Phalcon\DevTools\Commands\Builtin\Console;
use Phalcon\DevTools\Commands\Builtin\Controller;
use Phalcon\DevTools\Commands\Builtin\Enumerate;
use Phalcon\DevTools\Commands\Builtin\Info;
use Phalcon\DevTools\Commands\Builtin\Migration;
use Phalcon\DevTools\Commands\Builtin\Model;
use Phalcon\DevTools\Commands\Builtin\Module;
use Phalcon\DevTools\Commands\Builtin\Project;
use Phalcon\DevTools\Commands\Builtin\Scaffold;
use Phalcon\DevTools\Commands\Builtin\Serve;
use Phalcon\DevTools\Commands\Builtin\Webtools;
use Phalcon\DevTools\Commands\CommandsListener;
use Phalcon\DevTools\Commands\DotPhalconMissingException;
use Phalcon\DevTools\Script;
use Phalcon\DevTools\Script\Color;
use Phalcon\Devtools\Version;
use Phalcon\Events\Manager as EventsManager;
use Phalcon\Exception as PhalconException;

try {
    require dirname(__FILE__) . '/bootstrap/autoload.php';

    $vendor = sprintf('Phalcon DevTools (%s)', Version::get());
    print PHP_EOL . Color::colorize($vendor, Color::FG_GREEN, Color::AT_BOLD) . PHP_EOL . PHP_EOL;

    $eventsManager = new EventsManager();

    $eventsManager->attach('command', new CommandsListener());

    $script = new Script($eventsManager);

    $commandsToEnable = [
        Info::class,
        Enumerate::class,
        Controller::class,
        Module::class,
        Model::class,
        AllModels::class,
        Project::class,
        Scaffold::class,
        Migration::class,
        Webtools::class,
        Serve::class,
        Console::class,
    ];

    $script->loadUserScripts();

    foreach ($commandsToEnable as $command) {
        $script->attach(new $command($script, $eventsManager));
    }

    $script->run();
} catch (DotPhalconMissingException $e) {
    fwrite(STDERR, Color::info($e->getMessage() . " " . $e->scanPathMessage()));
    if ($e->promptResolution()) {
        $script->run();
    } else {
        exit(1);
    }
} catch (PhalconException $e) {
    fwrite(STDERR, Color::error($e->getMessage()) . PHP_EOL);
    exit(1);
} catch (Exception $e) {
    fwrite(STDERR, 'ERROR: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
