<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $databaseName
 * @var string $tables
 * @var string $templateEngines
 * @var string $directory
 */
?>

<?php echo $this->getContent() ?>

<h1>Generate Scaffold</h1>

<form method="post"  autocomplete="off" class="form-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/scaffold/generate") ?>">

    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <td><b>Schema</b></td>
            <td><?php echo $this->tag->textField(array('schema', 'value' => $databaseName)) ?></td>
        </tr>
        <tr>
            <td><b>Table name</b></td>
            <td><i><?php echo $this->tag->selectStatic('tableName', $tables) ?></i></td>
        </tr>
        <tr>
            <td><b>Template engine</b></td>
            <td><i><?php echo $this->tag->selectStatic('templateEngine', $templateEngines) ?></i></td>
        </tr>
        <tr>
            <td><b>Model's namespace</b></td>
            <td><i><?php echo $this->tag->textField(array('modelsNamespace')) ?></i></td>
        </tr>
        <tr>
            <td><b>Project Root</b></td>
            <td><i><?php echo $this->tag->textField(array('directory', 'value' => $directory)) ?></i></td>
        </tr>
        <tr>
            <td><b>Add setters and getters</b></td>
            <td><?php echo $this->tag->checkField(array('genSettersGetters', 'value' => 1)) ?></td>
        </tr>
        <tr>
            <td><b>Force</b></td>
            <td><?php echo $this->tag->checkField(array('force', 'value' => 1)) ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <div align="right">
                    <input type="submit" class="btn btn-primary" value="Generate"/>
                </div>
            </td>
        </tr>
    </table>
</form>
