<div class="span9">

	<?php echo $this->getContent() ?>

	<p><h1>Generate Scaffold</h1></p>

	<form method="post"  autocomplete="off" class="forma-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/scaffold/generate") ?>">

		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<td><b>Schema</b></td>
				<td><?php echo Phalcon\Tag::textField(array('schema', 'value' => $databaseName)) ?></td>
			</tr>
			<tr>
				<td><b>Table name</b></td>
				<td><i><?php echo Phalcon\Tag::selectStatic('tableName', $tables) ?></i></td>
			</tr>
			<tr>
				<td><b>Add setters and getters</b></td>
				<td><i><input type="checkbox" name="genSettersGetters" value="1"/></i></td>
			</tr>
			<tr>
				<td><b>Force</b></td>
				<td><i><input type="checkbox" name="force" value="1"/></i></td>
			</tr>
			<tr>
				<td colspan="2">
					<div align="right">
						<input type="submit" class="btn btn-primary" value="Generate"/>
					</div>
				</td>
			</tr>
		</table>

	</form>

</div>