
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("$plural$/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("$plural$", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit $plural$</h1>
</div>

<table>
$captureFields$
	<tr>
		<td><?php echo $this->tag->hiddenField("id") ?></td>
		<td><?php echo $this->tag->submitButton("Save") ?></td>
	</tr>
</table>

</form>
