<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("$plural$/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("$plural$/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<table class="table">
    <thead>
        <tr>
$headerColumns$
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $singularVar$): ?>
        <tr>
$rowColumns$
            <td><?php echo $this->tag->linkTo(array("$plural$/edit/" . $singularVar$->$pk$, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("$plural$/delete/" . $singularVar$->$pk$, "Delete")); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tbody>
        <tr>
            <td>
                <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                    <?php echo $page->current, "/", $page->total_pages ?>
                </p>
            </td>
            <td colspan="6">
                <nav>
                    <ul class="pagination">
                        <li><?php echo $this->tag->linkTo("$plural$/search", "First") ?></li>
                        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->before, "Previous") ?></li>
                        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->next, "Next") ?></li>
                        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->last, "Last") ?></li>
                    </ul>
                </nav>
            </td>
        </tr>
    </tbody>
</table>
