<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var array $tables
 * @var string|null $migrationsDir
 * @var string $version
 */
?>

<?php echo $this->getContent() ?>

<h1>Generate  Migration</h1>

<form method="POST" class="form-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/migrations/generate") ?>">

    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <td><b>Current Version</b></td>
            <td><i><?php echo $version ?></i></td>
        </tr>
        <tr>
            <td><b>New Version</b></td>
            <td><?php echo $this->tag->textField(array('version', 'placeholder' => 'Let empty to auto new version')) ?></td>
        </tr>
        <tr>
            <td><b>Table name</b></td>
            <td><?php echo $this->tag->selectStatic('table-name', $tables) ?></td>
        </tr>
        <tr>
            <td><b>Migrations Dir</b></td>
            <td><?php echo $this->tag->textField(array('migrationsDir', 'value' => $migrationsDir)) ?></td>
        </tr>
        <tr>
            <td><b>Force</b></td>
            <td><?php echo $this->tag->checkField(array('force', 'value' => 1)) ?></td>
        </tr>
        <tr>
            <td><b>Disable auto increment</b></td>
            <td><?php echo $this->tag->checkField(array('noAi', 'value' => 1)) ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <div align="right">
                    <input type="submit" class="btn btn-primary" value="Generate"/>
                </div>
            </td>
        </tr>
    </table>
</form>
