<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $version
 */
?>

<h1 class="page-header">Run Migration</h1>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form method="post" action="<?php echo $this->url->get("webtools.php?_url=/migrations/run") ?>">
            <div class="form-group disabled">
                <label for="oldVersion" class="col-sm-2 control-label">Current Version</label>
                <div class="col-sm-4">
                    <?php echo $this->tag->textField(array('oldVersion', 'value' => $version,  'disabled' => 'disabled', 'class' => 'form-control', 'id' => 'oldVersion')) ?>
                </div>
                <div class="col-sm-4 text-right">
                    <button type="submit" class="btn btn-danger btn-lg">Run</button>
                </div>
            </div>
        </form>
    </div>
</div>
