<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

?>
<?php echo $this->getContent() ?>

<h1>Run Migration</h1>

<form method="post" class="form-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/migrations/run") ?>">

    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <td><b>Current Version</b></td>
            <td><i><?php echo $version ?></i></td>
        </tr>
        <tr>
            <td colspan="2">
                <div align="right">
                    <input type="submit" class="btn btn-primary" value="Run"/>
                </div>
            </td>
        </tr>
    </table>

</form>
