<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $databaseName
 * @var string $tables
 * @var string $directory
 */
?>

<h1 class="page-header">Generate Models</h1>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="row">
            <form class="form-horizontal" autocomplete="off" method="post" action="<?php echo $this->url->get("webtools.php?_url=/models/create") ?>">
                <div class="form-group">
                    <label for="schema" class="col-sm-4 control-label">Schema</label>
                    <div class="col-sm-8">
                        <?php echo $this->tag->textField(array('schema', 'value' => $databaseName,  'placeholder' => 'Database name', 'class' => 'form-control', 'id' => 'schema')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="tableName" class="col-sm-4 control-label">Table name</label>
                    <div class="col-sm-8">
                        <?php echo $this->tag->selectStatic(array('tableName', 'class' => 'form-control', 'id' => 'tableName'), $tables); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="namespace" class="col-sm-4 control-label">Namespace</label>
                    <div class="col-sm-8">
                        <?php echo $this->tag->textField(array('namespace', 'placeholder' => 'eg. My\Awesome\Namespace', 'class' => 'form-control', 'id' => 'namespace')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="directory" class="col-sm-4 control-label">Project Root</label>
                    <div class="col-sm-8">
                        <?php echo $this->tag->textField(array('directory', 'value' => $directory, 'placeholder' => 'Absolute path to the project', 'class' => 'form-control', 'id' => 'directory')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <div class="checkbox">
                            <label for="genSettersGetters">
                                <?php echo $this->tag->checkField(array('genSettersGetters', 'id' => 'genSettersGetters', 'value' => 1)) ?> Add setters and getters
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <div class="checkbox">
                            <label for="foreignKeys">
                                <?php echo $this->tag->checkField(array('foreignKeys', 'id' => 'foreignKeys', 'value' => 1)) ?> Set Foreign Keys
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <div class="checkbox">
                            <label for="defineRelations">
                                <?php echo $this->tag->checkField(array('defineRelations', 'id' => 'defineRelations', 'value' => 1)) ?> Define Relations
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <div class="checkbox">
                            <label for="mapcolumn">
                                <?php echo $this->tag->checkField(array('mapcolumn', 'id' => 'mapcolumn', 'value' => 1)) ?> Generate map columns
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <div class="checkbox">
                            <label for="force">
                                <?php echo $this->tag->checkField(array('force', 'id' => 'force', 'value' => 1)) ?> Force
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8 text-right">
                        <button type="submit" class="btn btn-primary">Generate</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
