<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var null|string $modelsDir
 */
?>

<?php echo $this->getContent() ?>

<h1>Edit Models</h1>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<td><b>Name</b></td>
			<td><b>Size</b></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
        <?php if (!$modelsDir): ?>
        <tr>
            <td colspan="3">
                <p class="text-center text-error">
                    Sorry, Web Tools doesn't know where is the models directory. <br>
                    Please add to <code>application</code> section <code>modelsDir</code> param with valid path.
                </p>
            </td>
        </tr>
        <?php else: ?>
            <?php $iterator = new DirectoryIterator($modelsDir); foreach($iterator as $file): ?>
                <?php if (!$file->isDot()): ?>
                    <tr>
                        <td><?php echo $file->getFileName() ?></td>
                        <td><?php echo $file->getSize() ?></td>
                        <td>
                            <a href="<?php echo $this->url->get(sprintf('webtools.php?_url=/models/edit/%s', $file->getFileName())) ?>" class="btn">Edit</a>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
	</tbody>
</table>
