<?php 

namespace Phalcon\Forms {

	/**
	 * Phalcon\Forms\Form
	 *
	 * This component allows to build forms
	 */
	
	class Form {

		protected $_entity;

		protected $_elements;

		protected $_messages;

		/**
		 * \Phalcon\Forms\Form constructor
		 *
		 * @param boolean $entity
		 */
		public function __construct($entity=null){ }


		/**
		 *
		 * @param array|object $data
		 * @param object $entity
		 * @return boolean
		 */
		public function isValid($data=null, $entity=null){ }


		/**
		 * Returns the messages generated in the validation
		 *
		 * @return array
		 */
		public function getMessages($byItemName=null){ }


		/**
		 * Returns the messages generated by
		 *
		 * @return \Phalcon\Validation\Message\Group[]
		 */
		public function getMessagesFor($name){ }


		/**
		 * Adds an element to the form
		 *
		 * @param \Phalcon\Forms\ElementInterface $element
		 * @return \Phalcon\Forms\Form
		 */
		public function add($element){ }


		/**
		 * Renders an specific item in the form
		 *
		 * @param string $name
		 * @param array $attributes
		 * @return string
		 */
		public function render($name, $attributes=null){ }


		/**
		 * Returns an element added to the form by its name
		 *
		 * @param string $name
		 * @return \Phalcon\Forms\ElementInterface
		 */
		public function get($name){ }

	}
}
