<div class="span7">

	<?php echo $this->getContent() ?>

	<p><h1>Edit Configuration</h1></p>

	<form method="post" autocomplete="off" action="<?php echo $this->url("webtools.php?_url=config/save") ?>">

		<p>
			<div align="right">
				<input type="submit" class="btn btn-primary" value="Save"/>
			</div>
		</p>

		<?php

			foreach($posibleConfig as $section => $config){
				echo '<p><h3>', $section, '</h3></p>';
				echo '<table class="table table-striped table-bordered table-condensed">';
				foreach($config as $name => $type){
					if(isset($settings->$section->$name)){
						$value = $settings->$section->$name;
					} else {
						$value = '';
					}
					echo '<tr>
						<td><b>', $name, '</b></td>
						<td>', Phalcon_Tag::textField(array($name, 'value' => $value)), '</i></td>
					</tr>';
				}
				echo '</table>';
			}

		?>

	</form>

</div>
