<?php
/**
 * Local variables
 *
 * @var \Phalcon\Mvc\View\Engine $this
 */
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon // Web DevTools</title>
    <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.min.css') ?>
    <?php echo $this->tag->stylesheetLink('css/bootstrap/dashboard.css') ?>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <?php echo $this->getContent() ?>
        </div>
    </div>
    <?php echo $this->tag->javascriptInclude('js/jquery/jquery-3.1.0.min.js') ?>
    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js') ?>
</body>
</html>
