<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Phalcon // Web DevTools</title>
		<?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.min.css') ?>
        <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap-responsive.min.css') ?>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a href="webtools.php" class="brand">Phalcon Web Tools</a>
					<div class="nav-collapse">
						<ul class="nav"><?php echo Phalcon\Web\Tools::getNavMenu($this->view->getControllerName()) ?></ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span2">
				    <div class="well">
						<ul class="nav nav-list">
							<?php Phalcon\Web\Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
						</ul>
					</div>
				</div>
				<div class="span10 well">
					<?php echo $this->getContent() ?>
				</div>
			</div>
	    </div>
        <?php echo $this->tag->javascriptInclude('js/jquery/jquery.min.js') ?>
	    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js') ?>
	</body>
</html>
