<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */
?>

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Phalcon // Web DevTools</title>
		<?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.min.css') ?>
		<?php echo $this->tag->stylesheetLink('css/bootstrap/dashboard.css') ?>
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
	</head>
	<body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="webtools.php">Phalcon WebTools</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right"><?php echo Phalcon\Web\Tools::getNavMenu($this->view->getControllerName()) ?></ul>
                </div>
            </div>
        </nav>
		<div class="container-fluid">
			<div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <?php Phalcon\Web\Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
                    </ul>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?php echo $this->getContent() ?>
                </div>
			</div>
	    </div>
        <?php echo $this->tag->javascriptInclude('js/jquery/jquery-2.1.4.min.js') ?>
	    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js') ?>
	</body>
</html>
