<div class="span9">

	<?php echo $this->getContent() ?>

	<p><h1>Create Controller</h1></p>

	<form method="post" autocomplete="off" class="forma-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/controllers/create") ?>">
		<fieldset>
			<div class="control-group">
				<label class="control-label" for="name">Controller name</label>
				<div class="controls">
					<?php echo Phalcon\Tag::textField(array('name', 'placeholder' => 'Name ...')) ?>
				</div>
			</div>
			<label class="checkbox">
				<input type="checkbox" name="force" value="1"/>Force
			</label>
			<div align="right">
				<input type="submit" class="btn btn-primary" value="Generate"/>
			</div>
		</fieldset>
	</form>

</div>