<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

?>
<?php echo $this->getContent() ?>

<h1>Create Controller</h1>

<form method="post" autocomplete="off" class="form-horizontal" action="<?php echo $this->url->get("webtools.php?_url=/controllers/create") ?>">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="name">Controller name</label>
            <div class="controls">
                <?php echo $this->tag->textField(array('name', 'placeholder' => 'Class name')) ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="namespace">Namespace</label>
            <div class="controls">
                <?php echo $this->tag->textField(array('namespace')) ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="baseClass">Base class</label>
            <div class="controls">
                <?php echo $this->tag->textField(array('baseClass')) ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="directory">Project Root</label>
            <div class="controls">
                <?php echo $this->tag->textField(array('directory', 'value' => $directory)) ?>
            </div>
        </div>

        <label class="checkbox">
            <input type="checkbox" name="force" value="1"/>Force
        </label>
        <div align="right">
            <input type="submit" class="btn btn-primary" value="Generate"/>
        </div>
    </fieldset>
</form>
