<?php
/**
 * Local variables
 *
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $code
 * @var string $message
 * @var string $headMessage
 */
?>

<div class="col-md-8 col-md-offset-2">
    <div class="error-area jumbotron">
        <h1><?php echo $code ?></h1>
        <h3><?php echo $headMessage ?></h3>
        <p class="lead">
            <?php echo $message ?>
        </p>

        <?php echo $this->getContent() ?>
    </div>
</div>
